- name: install tomcat service
  hosts: node1
  become: true
  tasks:
   - name: install java
     apt:
        name: openjdk-8-jdk
        state: present
   - name: download tomcat server package
     get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.75/bin/apache-tomcat-8.5.75.tar.gz
        dest: /usr/local
        mode: 777
        
   - name: extract package
     unarchive: 
        src: /usr/local/apache-tomcat-8.5.75.tar.gz
        dest: /usr/local
        remote_src: yes
   - name: start server
     shell: nohup /usr/local/apache-tomcat-8.5.75/bin/startup.sh
   - name: give permission
     shell: chmod 777  -R /usr/local/apache-tomcat-8.5.75
   - name: copy file
     copy:
      src: shell.sh
      dest: /home/ubuntu
      mode: 777
   - name: execute
     shell: /home/ubuntu/shell.sh
   - name: copy
     copy:
      src: /home/ubuntu/gamutkart2/target/gamutgurus.war
      dest: /usr/local/apache-tomcat-8.5.75/webapps
      remote_src: yes

